name: Issue Comment Automation  
  
# 触发条件：当仓库中有新的issue被创建时  
on:  
  issues:  
    types: [opened]  
  
jobs:  
  send-issue-content:  
    runs-on: ubuntu-latest  
    steps:
      # 获取新创建的issue的详细信息  
      - name: Get issue details  
        id: issue  
        uses: octokit/request-action@main
        with:  
          route: GET /repos/:repository/issues/:issue_number
          repository: ${{ github.repository }}  
          issue_id: ${{ github.event.id }}
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  
      # 将issue的内容发送到特定的外部URL，并设置超时时间为3分钟  
      - name: Send issue content to external URL  
        id: send_request  
        uses: fjogeleit/http-request-action@v1
        with:  
          url: 'http://47.120.64.144:8080/github-issue' # 替换为你的实际URL  
          method: 'POST'  
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"title": "${{ github.event.issue.title }}", "body": "${{ github.event.issue.body }}"}'
          timeout: 180000 # 设置超时时间为180秒（3分钟）  

      # 若请求成功，进行评论
      - name: Comment on issue with response  
        if: steps.send_request.outputs.status == 200  
        uses: hasura/comment-progress@v2.3.0
        with:  
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}  
          number: ${{ github.event.id }}
          message: |  
            Response from external service:  
            ```  
            ${{ steps.send_request.outputs.response }}  
            ```  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  
      # 如果请求失败（例如超时或网络错误），可以选择添加一个错误评论  
      - name: Comment on issue with error  
        if: steps.send_request.outputs.status != 200  
        uses: peter-evans/commit-comment@v3
        with:  
          issue-number: 1
          body: |  
            Failed to get response from external service. Status code: ${{ steps.send_request.outputs.status }}  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
